config/routes.rb
Rails.application.routes.draw do


  get 'why-donate-leftovers-to-food-banks', to:'static_pages#why_donate', as:'why_donate'

  get 'current-donations', to: 'donations#current_donations', as:'current_donations'

  devise_for :users

  resources :users do
    resources :donations do
      member do
        get 'confirmation', to: 'donations#confirmation'
        get 'claim', to: 'donations#claim'
        get 'picked_up', to: 'donations#picked_up'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "dashboard/donor", to:"dashboard#donor_dashboard", as:"donor_dashboard"
  get "dashboard/food_bank", to:"dashboard#food_bank_dashboard", as:"food_bank_dashboard"

  get "about", to: "static_pages#about", as: "about"

  root to: "static_pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donor, :class_name => "User", :inverse_of => :donor_donations
  belongs_to :food_bank, :class_name => "User", :inverse_of => :food_bank_donations, required: false

  scope :fresh, -> {where("expires > ?", Time.now)}
  scope :unclaimed, -> {where("food_bank_id IS NULL")}
  scope :expired, -> {where("expires < ?", Time.now)}
  scope :pending, -> {where("food_bank_id IS NOT NULL").where(picked_up:false)}
  scope :picked_up, -> {where("food_bank_id IS NOT NULL").where(picked_up:true)}

  def latitude
    donor.latitude
  end

  def longitude
    donor.longitude
  end

  def claim!(food_bank)
    update_columns(food_bank_id:food_bank.id)
  end

  def picked_up!
    update_columns(picked_up:true)
  end

  def claimed?
    true if food_bank_id.present?
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 geocoded_by :full_street_address
 after_validation :geocode

 has_many :donor_donations, :class_name => 'Donation', :foreign_key => "donor_id"
 has_many :food_bank_donations, :class_name => 'Donation', :foreign_key => "food_bank"

 def full_street_address
   location_array = Array.new
   location_array << address_1 if address_1.present?
   location_array << city if city.present?
   location_array << state if state.present?
   location_array << zip_code if zip_code.present?
   [location_array].join(', ')
 end

 def food_bank?
   true if role == "food_bank"
 end

 def donor?
   true if role == "donor"
 end

 def full_name
   "#{first_name} #{last_name}"
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :name, :first_name, :last_name, :address_1, :address_2, :city, :zip_code, :state, :country, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role, :name, :first_name, :last_name, :address_1, :address_2, :city, :zip_code, :state, :country, :phone])

  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def donor_dashboard
  end

  def food_bank_dashboard
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end


  # GET /donations/new
  def new
    @donation = current_user.donor_donations.build
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = current_user.donor_donations.build(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to root_url, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to root_url, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def current_donations
    @donations = Donation.fresh.unclaimed
  end

  def claim
    @donation = Donation.find(params[:id])
    if @donation.food_bank_id.blank?
      @donation.claim!(current_user)
      DonationsMailer.confirmation_email(@donation).deliver_now
      redirect_to confirmation_user_donation_path(@donation.donor, @donation)
    else
      flash[:error] = "That donation has been claimed"
      redirect_to current_donations_path
    end
  end

  def picked_up
    @donation = Donation.find(params[:id])
    @donation.picked_up = true
    @donation.save
    redirect_to root_path
  end

  def confirmation
    @donation = Donation.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      if current_user.food_bank?
        @donation = current_user.food_bank_donations.find(params[:id])
      else
        @donation = current_user.donor_donations.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:description, :expires, :donor_id, :food_bank_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :check_signed_in, only:[:home]

  def home
  end

  def about
  end

  def why_donate
  end

  private

  def check_signed_in
    if current_user.present?
      if current_user.food_bank?
        redirect_to food_bank_dashboard_path
      else
        redirect_to donor_dashboard_path
      end
    end
  end

end

app/helpers/address_helper.rb
module AddressHelper

  def display_address(user)
    address_html = ''
    address_html += "#{user.full_name} " if user.full_name.present?
    address_html += "<br>#{user.address_1}" if user.address_1.present?
    address_html += "<br>#{user.address_2}" if user.address_2.present?
    address_html += "<br>#{user.city}, #{user.state} #{user.zip_code}" if (user.city.present? && user.state.present? && user.zip_code.present?)
    address_html += "<br>P: #{user.phone}" if user.phone.present?
    address_html += "<br>E: #{user.email}" if user.email.present?

    return address_html
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper

  def generate_map_url(donations, zoom=10)
   url = "http://maps.googleapis.com/maps/api/staticmap?center="
   # Center the Map on the Food Bank viewing it
   url += "#{current_user.latitude},#{current_user.longitude}"
   # Add each donation as a marker
   donations.each_with_index do |d, i|
     url += "&markers=color:blue|label:#{i+1}|#{d.latitude},#{d.longitude}"
   end
   # Add zoom, size, and api key info
   url +=  "&zoom=#{zoom}&size=1280x800&key=#{ENV['GOOGLE_MAPS_API_KEY']}"
   return url
  end


end

app/helpers/svg_helper.rb
module SvgHelper

  def render_svg(name)
    file_path = "#{Rails.root}/app/assets/images/icons/svg/#{name}.svg"
    if File.exists?(file_path)
      return File.read(file_path).html_safe
    else
      return '(not found)'
    end
  end

end

app/views/dashboard/donor_dashboard.html.haml
.page-wrapper
  .container
    .row
      .col-sm-12
        %h1.text-center Welcome, #{current_user.name}!
        %br
        %br


        .white-bg
          %h3 Log a Donation
          %p Do you have leftovers you'd like to let nearby food banks know about? Use the link below to log a new donation and your local charities will be able to claim it and connect with you.
          .text-center.margin-top-bottom-10
            = link_to "<span class='fa fa-cutlery'></span>New Donation".html_safe, new_user_donation_path(current_user), class:'btn btn-lg btn-success'

    .row
      .col-sm-12
        .white-bg
          %h3 Your Pending Donations
          - if current_user.donor_donations.fresh.present?
            = render partial: 'donations/donor_pending_donation_summary', locals:{donations:current_user.donor_donations.fresh}
          - else
            %p.text-center
              You don't have any pending donations
    .row
      .col-sm-12
        .white-bg
          %h3 Your Past Donations
          - if current_user.donor_donations.expired.present?
            = render partial: 'donations/donor_donation_summary', locals:{donations:current_user.donor_donations.expired}
          - else
            %p.text-center
              You don't have any past donations

app/views/dashboard/food_bank_dashboard.html.haml
.page-wrapper
  .container
    .row
      .col-sm-12
        %h1.text-center Welcome, #{current_user.name}!
        %br
        %br

        .white-bg
          %h3 Browse Current Donations
          %p You can search through all of the restaurants who currently are offering a food donation for pickup.
          .text-center.margin-top-bottom-10
            = link_to "<span class='fa fa-cutlery'></span>View Current Donations".html_safe, current_donations_path, class:'btn btn-lg btn-success'

    .row
      .col-sm-12
        .white-bg
          %h3 Your Pending Donations
          %p These are the donations you've claimed. It's your job to coordinate pickup with the restaurant!

          - if current_user.food_bank_donations.pending.present?
            = render partial: 'donations/food_bank_pending_donation_summary', locals:{donations:current_user.food_bank_donations.pending}
          - else
            %p.text-center
              You don't have any pending donations
    .row
      .col-sm-12
        .white-bg
          %h3 Your Past Donations
          - if current_user.food_bank_donations.picked_up.present?
            = render partial: 'donations/food_bank_donation_summary', locals:{donations:current_user.food_bank_donations.picked_up}
          - else
            %p.text-center
              You don't have any past donations

app/views/donations/_donor_donation_summary.html.haml
%table.table
  %thead
    %tr
      %th
      %th
        Donation Description
      %th
        Status
      %th

  %tbody
    - donations.each do |donation|
      %tr
        %td
          = donation.created_at.strftime('%b %-d')
        %td
          = donation.description
        %td
          - if donation.food_bank_id.present?
            Picked up by #{donation.food_bank}
          - else
            Unclaimed

app/views/donations/_donor_pending_donation_summary.html.haml
%table.table
  %thead
    %tr
      %th
      %th
        Donation Description
      %th
        Status
      %th
        Expires

  %tbody
    - donations.each do |donation|
      %tr
        %td
          = donation.created_at.strftime('%b %-d')
        %td
          = donation.description
        %td
          - if donation.food_bank_id.present?
            Claimed by: #{donation.food_bank.name}
            %br
            = (display_address donation.food_bank).html_safe

          - else
            Unclaimed
        %td
          = donation.expires.strftime('%b %-d %H:%M %Z')
        %td
          -if !donation.claimed?
            = link_to 'Destroy', user_donation_path(current_user, donation), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-sm btn-danger'

app/views/donations/_food_bank_donation_summary.html.haml
%table.table
  %thead
    %tr
      %th
      %th
        Donor
      %th
        Donation Description

  %tbody
    - donations.each do |donation|
      %tr
        %td
          = donation.created_at.strftime('%b %-d')
        %td
          = donation.donor.name
          %br
          = (display_address donation.donor).html_safe
        %td
          = donation.description

app/views/donations/_food_bank_pending_donation_summary.html.haml
%table.table
  %thead
    %tr
      %th
        Restaurant
      %th
        Donation Description
      %th
        Expires

  %tbody
    - donations.each do |donation|
      %tr
        %td
          = donation.donor.name
          %br
          = (display_address donation.donor).html_safe
        %td
          = donation.description
        %td
          = donation.expires.strftime('%b %-d %H:%M %Z')
        %td
          = link_to "<span class='fa fa-truck'></span> Picked up!".html_safe, picked_up_user_donation_path(donation.donor, donation), class:'btn btn-success btn-block btn-md'

app/views/donations/_form.html.haml
= form_for([current_user, donation]) do |f|
  - if donation.errors.any?
    #error_explanation
      %h2
        = pluralize(donation.errors.count, "error")
        prohibited this donation from being saved:
      %ul
        - donation.errors.full_messages.each do |message|
          %li= message

  %fieldset
    .legend
      %legend
        %span.fa.fa-cutlery
        Donation information

    .form-group
      = f.label :description, class:'control-label'
      = f.text_area :description, class:'form-control', rows:4
      %p.help-block
        Let food banks know what you have? What type of food? How much? What type of packaging?
    .form-group
      = f.label :expires, class:'control-label'
      = f.datetime_select :expires
      %p.help-block
        When does the charity you connect with have to pick this donation up by?

    = f.hidden_field :donor_id, value:current_user.id
    .actions
      = f.submit class:'btn btn-success btn-lg'

app/views/donations/confirmation.html.haml
.page-wrapper
  %h1.text-center Donation Claimed!
  .container
    .row
      .col-md-12
        .white-bg.text-center
          .text-hero
            Your next step is to contact the restaurant donating the food. Call their contact person at the number below. A confirmation email has been sent to both you and the restaurant.


            %hr
            .row
              .col-sm-6
                %h3
                  = @donation.donor.name

                = (display_address @donation.donor).html_safe

              .col-sm-6
                = image_tag generate_map_url([@donation], zoom:12), class: 'img-rounded img-responsive', alt: "Nearby restaurants donating food now"

app/views/donations/current_donations.html.haml
.page-wrapper
  %h1.text-center Current Donations
  .container
    .row
      .col-md-12
        .white-bg
          = image_tag generate_map_url(@donations), class: 'img-rounded img-responsive', alt: "Nearby restaurants donating food now"

        - @donations.each_with_index do |donation, index|
          .row.donation-row
            .col-md-12
              .white-bg
                .row
                  .col-md-3
                    %h3
                      %span.restaurant-name
                        %span.badge
                          = index + 1
                        = donation.donor.name
                    %address
                      = (display_address donation.donor).html_safe
                  .col-md-6
                    %span.description
                      = simple_format donation.description
                      .alert.alert-danger.text-bold.text-center.expires-notice
                        Expires #{donation.expires.strftime('%b %-d %H:%M %Z')}

                  .col-md-3
                    %span.donation-links
                      = link_to "<span class='fa fa-cutlery'></span>Claim Donation".html_safe, claim_user_donation_path(donation.donor, donation), class:'btn btn-success btn-block btn-md'

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Expires</th>
      <th>Donor</th>
      <th>Food bank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.description %></td>
        <td><%= donation.expires %></td>
        <td><%= donation.donor_id %></td>
        <td><%= donation.food_bank_id %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.haml
.page-wrapper
  %h1.text-center New Donation
  .container
    .row
      .col-md-10.col-md-offset-1
        .form-wrapper
          = render 'form', donation: @donation

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @donation.description %>
</p>

<p>
  <strong>Expires:</strong>
  <%= @donation.expires %>
</p>

<p>
  <strong>Donor:</strong>
  <%= @donation.donor_id %>
</p>

<p>
  <strong>Food bank:</strong>
  <%= @donation.food_bank_id %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/layouts/_footer.html.haml
%footer

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_url} Urban Harvest
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if current_user.present?
          %li
            = link_to "<span class='fa fa-dashboard'></span>Dashboard".html_safe, root_path

        %li
          = link_to "<span class='fa fa-info-circle'></span>Why donate?".html_safe, why_donate_path

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %span.fa.fa-user
              My Account
              %span.caret
            %ul.dropdown-menu
              %li= link_to '<span class="fa fa-cog"></span> Account settings'.html_safe, edit_user_registration_path
              %li= link_to '<span class="fa fa-sign-out"></span> Sign out'.html_safe, destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Sign in', new_user_session_path

app/views/layouts/_notifications.html.haml
#notification-growl
  - flash.each do |key, value|
    = content_tag :div, (value.html_safe if value), class: "flash #{(key if key)}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrbanHarvest</title>
    <%= csrf_meta_tags %>

    <!-- Cutlery Favicon -->
    <link href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA/7cAAP+EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAACAAAAAiIAACIgAAACIgAAIiAAAAIiAAAiIAAAAiIAACIgAAACIgAAIiAAAAIiAAAiIAAAEREQABERAAARERAAEREQABAQEAARERAAEBAQABEREAAQEBAAEREQABAQEAAREQAAEBAQABEAAAAAAAAAAAAAAAAAAAAAAAD37wAA48cAAOPHAADjxwAA48cAAOPHAADjxwAAwcMAAMHBAADVwQAA1cEAANXBAADVwwAA1c8AAP//AAD//wAA" rel="icon" type="image/x-icon" />

    <!-- Google Web Fonts -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,500,700,800,100,600" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Signika:300,400,600,700" rel="stylesheet">

    <!-- FontAwesome icons -->
    <script src="//use.fontawesome.com/f93edc0fec.js"></script>

    <!-- Latest compiled and minified Bootstrap 3 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- Latest compiled and minified Bootstrap 3 JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body class="<%= params[:controller] %>-<%= params[:action] %>">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/notifications' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.haml
%section#header.text-center
  .row
    .col-md-10.col-md-offset-1
      %h1.brand-name
        %span.paw
          %span.fa.fa-cutlery
        Urban Harvest

  .row.margin-top-40.text-center
    .col-sm-12
      = link_to "I am a Restaurant<br>and I'd like to donate leftovers".html_safe, new_user_registration_path(role:'donor'), class:'btn btn-lg btn-success'
      = link_to "I am a food bank<br>and I'd like to pickup leftovers".html_safe, new_user_registration_path(role:'food_bank'), class:'btn btn-lg btn-success'



%section.under-header-section
  .row
    .col-sm-12.text-center
      .svg-icon.svg-50
        = render_svg 'apple'
      %h3
        What is Urban Harvest?

      %p.hero-text
        Urban Harvest is a program that links restaurants with delicious leftover food with local food banks.  Allows direct communication between restaurants and food banks.  Let nothing be wasted.

%section
  .row
    .col-sm-12.text-center
      %h3
        How does it work?
      .row
        .col-sm-4
          .svg-icon.svg-100
            = render_svg 'porridge'
            %p.hero-text
              Restaurants have leftovers and log them on the site


        .col-sm-4
          .svg-icon.svg-100
            = render_svg 'maps-and-flags'
            %p.hero-text
              Charities can browse through all the nearby donations and connect with the donor

        .col-sm-4
          .svg-icon.svg-100
            = render_svg 'groceries'
            %p.hero-text
              Leftovers make their way to people who need it




%br
%br
%br
%br
%br
%br
%br
%br
%br
%br

app/views/static_pages/why_donate.html.haml
.page-wrapper
  %h1.text-center
    Why should a restaurant participate in Urban Harvest?

  .container
    .row
      .col-md-12
        .white-bg

          %h3
            You can make a difference and help end hunger in your community

          %p.text-hero
            Hunger remains the No.1 cause of death in the world. 
            %br
            There are 820 million chronically hungry people in the world.
            %br
            10 million people die every year of chronic hunger and hunger-related diseases. 
            %br
            48.8 million Americans—including 16.2 million children—lack the means to get enough nutritious food on a regular basis. 
           
          %h3
            Benefits

          %p.text-hero
          
            U.S. Congress enacted Section 170 of the Internal Revenue Code in 1976 to encourage donations by allowing corporations to earn an enhanced tax deduction for donating food.    

          %h3
            The waste

          %p.text-hero
            Americans throw away more than 25 percent of the food we prepare, about 96 billion pounds of food waste each year according to the US Department of Agriculture's



          %h3
            Vison

          %p.text-hero
          When they had all had enough to eat, Jesus said to his disciples, "Gather the pieces that are left over. Let nothing be wasted." John 6:12 (NIV)
            